### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aanandgupta**
User must be redirected issues page by clicking on the issue button on read me

### CODE REVIEW

**Comment by t0xic0der** [comment]
@Aanandgupta, thank you for your contributions. Please do let me know about the issue that you're solving with this pull request.

@khallnayak, tagging you for your reference.

**Comment by Aanandgupta** [comment]
I think wasn't added

> @Aanandgupta, thank you for your contributions. Please do let me know about the issue that you're solving with this pull request.
> 
> @khallnayak, tagging you for your reference.

when we are clicking on  images on readme we are been redirected to page where only image is present 
it would be better if for eg clicking on issue it redirects to issue column of the page

**Comment by t0xic0der** [comment]
@Aanandgupta That is true for the forks, stars, license and watchers icon as well, right?

I am wondering why you haven't created redirects for them too.

**Comment by t0xic0der** [comment]
Closing this PR and marking it as `invalid` as the author has not reverted back with an answer within a week of time.

**Pull request closed without merging**
